# Site settings
title: Landsbyologi
email:
description: > # this means to ignore newlines until "baseurl:"
  Jeg hedder Janni Teilmann.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://janniteilmann.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
